### ISSUE TITLE
Sleepy.bike does not have permission to use the logo

### ISSUE THREAD

**Issue by mrkvon** [OpenHospitalityNetwork/sleepy.bike#2]
I noticed somebody must have recently reverted my commit to [sleepy.bike](http://sleepy.bike/) repo that implemented logo removal. As a consequence, [sleepy.bike](http://sleepy.bike/) app displays my artwork without my consent. That logo does not belong to [sleepy.bike](http://sleepy.bike/) anymore.

For context, please see https://mrkvon.org/blog/announcing-solidcouch

**Comment by mariha** [comment]
The blinking eyes from [sleepy.bike](http://sleepy.bike/) logo that [you claim being your intellectual property](https://mrkvon.org/blog/announcing-solidcouch/) were [first designed and made by Parnia](https://github.com/solidcouch/solidcouch/issues/45#issuecomment-1646896354), as a community effort. 

I'll keep what we have as for now, with a plan to change computer-graphics version made by you for a hand-drawn version as initially described as desired in the GH issue comment linked above (and [archived here](https://web.archive.org/web/20241206125540/https://github.com/solidcouch/solidcouch/issues/45)).

**Comment by mrkvon** [comment]
> The blinking eyes from [sleepy.bike](http://sleepy.bike/) logo that [you claim being your intellectual property](https://mrkvon.org/blog/announcing-solidcouch/) were https://github.com/solidcouch/solidcouch/issues/45#issuecomment-1646896354, as a community effort.

There are two points I would like to point out as incorrect:

1. I didn't say anything about blinking eyes in the blog post. Please read it again (emphasis added):
  > I withdraw my implicit consent from OHN and Sleepy Bike for using my intellectual property, including but not limited to the logos and designs that I authored and hold copyright to: the **Bicycle chain link with tired or other eyes, and the connected chain links with diverse eyes and colors**.
2. Parnia's artwork is a derivative work based on my original artwork, here's a proof from my chat with Mariha:

#### July 2, 2022
me: _Idea for a logo. Is there some logo pool, or already chosen?_
![image](https://github.com/user-attachments/assets/d669063d-7dde-4ec1-b23f-8d4b0ac47192)

#### September 17, 2022
Mariha asks me for permission on behalf of Parnia:
![image](https://github.com/user-attachments/assets/123ae5c8-8988-4ea0-addb-2a0db83102b6)

8 hours later, I agree, and share the other part of my work:

me: _I was also thinking something like this, also in colors in 🏳️‍🌈 I thought, but colors don't fit your idea of simplicity._
and: _That adds a community feel ... Together_
![image](https://github.com/user-attachments/assets/a613e37e-5759-40bc-a84c-2086f976df6d)

#### November 20, 2022

Mariha shares [results in an issue](https://github.com/solidcouch/solidcouch/issues/45#issuecomment-1646896354).

It's safe to conclude that my work is the original work, and Parnia's work adds a nice touch of blinking eyes, but it is a derivative work. It also proves that my intellectual property claim is sound. @mariha, please reopen this issue, and respect my copyright. Thank you.

**Comment by mrkvon** [comment]
What is the hand-drawn logo you mention, @mariha? Is it the initial logo that I drew, displayed above, or something else?
